export default Object.freeze({
    IOL_GRANT_TYPE : 'password',
    IOL_API_HOST : 'https://api.invertironline.com',
    IOL_API_TOKEN : 'https://api.invertironline.com/token',
    IOL_API_STOCK_GET : 'https://api.invertironline.com/api/v2/$0/Titulos/$1',
    IOL_API_OPTIONS_GET : 'https://api.invertironline.com/api/v2/$0/Titulos/$1/Opciones',
    IOL_API_STOCK_PRICE_GET : 'https://api.invertironline.com/api/v2/$0/Titulos/$1/Cotizacion',
    IOL_API_PRICE_BOX : 'https://api.invertironline.com/api/v2/$0/Titulos/$1/Cotizacion',
    IOL_API_STOCK_HISTORY_GET : 'https://api.invertironline.com/api/v2/$0/Titulos/$1/Cotizacion/seriehistorica/$2/$3/$4',
    IOL_API_OPERATION : 'https://api.invertironline.com/api/v2/operaciones/$0',
    IOL_API_OPERATION_BUY : 'https://api.invertironline.com/api/v2/operar/Comprar',
    IOL_API_OPERATION_SELL : 'https://api.invertironline.com/api/v2/operar/Vender',
    OPTION_CALL_FLAG: 'C',
    OPTION_PUT_FLAG: 'V',
    IOL_API_ACCOUNT_STATUS : 'https://api.invertironline.com/api/v2/estadocuenta',
    IOL_API_ACCOUNT_PORTFOLIO : 'https://api.invertironline.com/api/v2/portafolio/$0',
});